### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'units' when using the NoisyDense Class

### ISSUE THREAD

**Issue by THINK989** [OctThe16th/NoisyDenseKeras#1]
Hello, 
I am actually new to Keras and I ran into an error when I used your class is my model as a layer.
Here the code: - 
```

self.model = self._model()
# target network
self.target_model = clone_model(self.model)
self.target_model.set_weights(self.model.get_weights())

 def _model(self):
      model = Sequential()
      model.add(Dense(units=128, activation="relu", input_dim=self.state_size))
      model.add(Dense(units=256, activation="relu"))
      model.add(Dense(units=256, activation="relu"))
      model.add(NoisyDense(128, activation="relu"))
      model.add(NoisyDense(self.action_size + 1, activation='linear'))
      model.compile(loss=self.loss, optimizer=self.optimizer)
      return model
```
also tried: - 

```
def _model(self):
        inp = Input((self.state_size,))
        x = Dense(units=128, activation="relu")(inp)
        x = Dense(units=256, activation="relu")(x)
        x = Dense(units=256, activation="relu")(x)
        x = NoisyDense(units = 128, activation="relu", sigma_init = 0.02)(x)
        out = NoisyDense(units  = self.action_size + 1, activation='linear',sigma_init = 0.02)(x)
        model = Model(inputs = inp, outputs = out)
        model.compile(loss=self.loss, optimizer=self.optimizer)
        return model
```

I ran into this error

```
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    pretrained=pretrained, debug=debug)
  File "train.py", line 52, in main
    agent = Agent(window_size, strategy=strategy, pretrained=pretrained, model_name=model_name)
  File "C:\Users\Desktop\agent.py", line 158, in __init__
    self.target_model = clone_model(self.model)
  File "D:\anaconda\lib\site-packages\keras\models.py", line 255, in clone_model
    return _clone_sequential_model(model, input_tensors=input_tensors)
  File "D:\anaconda\lib\site-packages\keras\models.py", line 207, in _clone_sequential_model
    layers = [clone(layer) for layer in model.layers]
  File "D:\anaconda\lib\site-packages\keras\models.py", line 207, in <listcomp>
    layers = [clone(layer) for layer in model.layers]
  File "D:\anaconda\lib\site-packages\keras\models.py", line 205, in clone
    return layer.__class__.from_config(layer.get_config())
  File "D:\anaconda\lib\site-packages\keras\engine\base_layer.py", line 1179, in from_config
    return cls(**config)
TypeError: __init__() missing 1 required positional argument: 'units'
```
How do I solve this error? Does it expect an input_dimension?
Thank you

**Comment by THINK989** [comment]
Hey, back again actually found the answer on StackOverflow
https://stackoverflow.com/questions/56104823/valueerror-unknown-layer-when-calling-copy-deepcopynetwork-using-tens

My model is training now. I will close the issue then. Thank You.
